<a href="https://colab.research.google.com/github/ArnabG99/Assignment-1/blob/ArnabG99/MLCC_NeuralNetwork(Single_Layer).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from sklearn import datasets
from pandas import DataFrame as df


In [0]:
iris = datasets.load_iris()
x = iris.data
y = iris.target
x = np.insert(x,x.shape[1],y,axis=1)
data = pd.DataFrame(x)

data = data.reindex(np.random.permutation(data.index))
data.head()

0    1    2    3    4
77   6.7  3.0  5.0  1.7  1.0
70   5.9  3.2  4.8  1.8  1.0
15   5.7  4.4  1.5  0.4  0.0
40   5.0  3.5  1.3  0.3  0.0
107  7.3  2.9  6.3  1.8  2.0

In [0]:
features = data.iloc[:,:4]
target = data.iloc[:,4]

target = target.values.reshape((target.shape[0],1))
target_class = np.zeros(shape=(target.shape[0],3))

for i in range(target.shape[0]):
  if target[i] == 0:
    target_class[i][0] = 1
  elif target[i] == 1:
    target_class[i][1] = 1
  else:
    target_class[i][2] = 1
    
print(target_class.shape)
print(target_class)



(150, 3)
[[0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0.

In [0]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

def der_sigmoid(x):
  return (sigmoid(x)*(1-sigmoid(x)))

In [0]:
input_nodes = features.shape[1]
output_nodes = 3;
weight_matrix = np.random.uniform(size=(input_nodes,output_nodes))

epoch = 2000 #increase it to increase accuracy
lr = 0.015  #learning rate decrease it to increase accuracy 

In [0]:
for i in range(epoch):
  output_node_input = features.dot(weight_matrix)
  output = sigmoid(output_node_input)
  
  error = target_class - output
  drv = der_sigmoid(output_node_input)
  delta_weight = error*drv
 
  weight_matrix = weight_matrix + lr*features.T.dot(delta_weight)

In [0]:
final_output = np.array(output)
#print(final_output) #test here
output_class = np.zeros(shape=final_output.shape[0])

for i in range(final_output.shape[0]):
  output_class[i] = np.argmax(final_output[i])

print(output_class) #test here
class_diff = output_class - target[:,0]

[1. 2. 0. 0. 1. 0. 0. 1. 1. 0. 2. 2. 1. 0. 1. 2. 0. 0. 0. 1. 0. 0. 0. 1.
 1. 1. 2. 1. 0. 2. 1. 2. 2. 0. 1. 0. 2. 2. 0. 1. 0. 0. 0. 0. 0. 0. 1. 2.
 2. 1. 0. 0. 2. 2. 0. 1. 2. 2. 0. 2. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 2. 1.
 1. 2. 2. 2. 2. 1. 1. 2. 1. 2. 2. 2. 0. 1. 1. 2. 1. 2. 2. 0. 1. 2. 1. 2.
 0. 0. 0. 1. 2. 2. 0. 1. 0. 0. 2. 2. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1.
 1. 0. 0. 2. 1. 1. 1. 1. 2. 0. 2. 1. 2. 1. 2. 2. 0. 2. 1. 0. 1. 0. 1. 2.
 2. 1. 2. 1. 2. 1.]


In [0]:
print('Actual Class')
print(target[:,0])
print('>>>>>>>>>>>>>>>>>>>>>>>>>>>>')
print('Predicted Class')
print(output_class)

wrong_prediction = np.count_nonzero(class_diff)
N = len(class_diff)
#print(class_diff)
simple_accuracy = 100 * (N-wrong_prediction)/N
print('Accuracy : ', (simple_accuracy), '%')

Actual Class
[1. 1. 0. 0. 2. 0. 0. 2. 1. 0. 2. 2. 1. 0. 1. 2. 0. 0. 0. 1. 0. 0. 0. 1.
 1. 1. 2. 1. 0. 2. 2. 2. 2. 0. 1. 0. 2. 2. 0. 2. 0. 0. 0. 0. 0. 0. 1. 2.
 2. 1. 0. 0. 2. 2. 0. 2. 2. 2. 0. 2. 0. 0. 1. 2. 0. 0. 0. 0. 1. 1. 2. 1.
 2. 2. 2. 2. 2. 1. 1. 2. 1. 2. 2. 2. 0. 1. 1. 2. 1. 2. 2. 0. 1. 1. 1. 2.
 0. 0. 0. 1. 2. 2. 0. 1. 0. 0. 2. 2. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 2. 1.
 1. 0. 0. 2. 1. 1. 1. 1. 2. 0. 2. 1. 2. 1. 2. 1. 0. 2. 1. 0. 1. 0. 1. 2.
 2. 1. 2. 1. 1. 1.]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Predicted Class
[1. 2. 0. 0. 1. 0. 0. 1. 1. 0. 2. 2. 1. 0. 1. 2. 0. 0. 0. 1. 0. 0. 0. 1.
 1. 1. 2. 1. 0. 2. 1. 2. 2. 0. 1. 0. 2. 2. 0. 1. 0. 0. 0. 0. 0. 0. 1. 2.
 2. 1. 0. 0. 2. 2. 0. 1. 2. 2. 0. 2. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 2. 1.
 1. 2. 2. 2. 2. 1. 1. 2. 1. 2. 2. 2. 0. 1. 1. 2. 1. 2. 2. 0. 1. 2. 1. 2.
 0. 0. 0. 1. 2. 2. 0. 1. 0. 0. 2. 2. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1.
 1. 0. 0. 2. 1. 1. 1. 1. 2. 0. 2. 1. 2. 1. 2. 2. 0. 2. 1. 0. 1. 0. 1. 2.
 2. 1. 2. 1. 2. 1.]
Accuracy :  92.0 %
